# SVD Example in Python

## Python SVD Basics

In [83]:
import numpy as np
from numpy import ndarray

In [2]:
X = np.random.normal(size=[20,18])
P, D, Q = np.linalg.svd(X, full_matrices=False)
X_a = np.matmul(np.matmul(P, np.diag(D)), Q)
print(np.std(X), np.std(X_a), np.std(X - X_a))

0.9644674918390902 0.9644674918390896 1.6600846198124851e-15


First lets define a matrix:

In [7]:
A = np.matrix('1 2 3; 4 5 6')
print (A)

[[1 2 3]
 [4 5 6]]


Next lets perform the SVD on that matrix:

In [140]:
U, S, V = np.linalg.svd(A, full_matrices = True)
print('U = \n', U, '\n\nS = \n', S, '\n\nV = \n', V)

U = 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]] 

S = 
 [9.508032   0.77286964] 

V = 
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Let's do the same thing but make S a diagonal matrix.
This is because numpy just gives the singular values without placing the zeros.

In [168]:
U, S, V = np.linalg.svd(A, full_matrices = True)
S = np.diag(S)
print('U = \n', U, '\n\nS = \n', S, '\n\nV = \n', V)

U = 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]] 

S = 
 [[9.508032   0.        ]
 [0.         0.77286964]] 

V = 
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Oops, S is not the right size still, we need S to have one more column of zeros:

In [173]:
S_dim = S.shape # create a tuple of the dimensions
S_new = np.zeros((S_dim[0], S_dim[1]+1)) # matrix of zeros one more column than S
print(S_new)

S_new[:,:-1] = S
print('\nU = \n', U, '\n\nS_new = \n', S_new, '\n\nV = \n', V)

[[0. 0. 0.]
 [0. 0. 0.]]

U = 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]] 

S_new = 
 [[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]] 

V = 
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Much better.

Now, lets varify that we can reconstruct A with these three matricies.

In [116]:
V.getH()

matrix([[-0.42866713,  0.80596391,  0.40824829],
        [-0.56630692,  0.11238241, -0.81649658],
        [-0.7039467 , -0.58119908,  0.40824829]])

In [118]:
U @ S_new @ V

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [48]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)

u, s, vh = np.linalg.svd(a, full_matrices=True)
u.shape, s.shape, vh.shape

np.allclose(a, np.dot(u[:, :6] * s, vh))

smat = np.zeros((9, 6), dtype=complex)
smat[:6, :6] = np.diag(s)
np.allclose(a, np.dot(u, np.dot(smat, vh)))

True

In [50]:
import numpy as np
X = np.random.normal(size=[20,18])
P, D, Q = np.linalg.svd(X, full_matrices=False)
X_a = P @ np.diag(D) @ Q
print(np.std(X), np.std(X_a), np.std(X - X_a))
print('Is X close to X_a?', np.isclose(X, X_a).all())

1.002606521919355 1.0026065219193547 1.3311551713181252e-15
Is X close to X_a? True


Python SVD on Image

View the documentation on the numpy linear algebra [here](https://docs.scipy.org/doc/numpy-1.16.1/reference/routines.linalg.html).